### PR TITLE
0.6.0 Support multi-root workspace feature 

### PR DESCRIPTION
**Pull request by hangxingliu**
## Description

The multi-workspace feature as a part of vscode stable since 1.18.0. 
<https://code.visualstudio.com/updates/v1_18#_support-for-multi-root-workspaces>

I add `vscode.window.showWorkspaceFolderPick` in extension and use it if multi folder workspace is opened. (Still compatible with the old version vscode).
and upgrade your extension typescript version from 1.x.x to 2.x.x (latest version)

### commit d7a50c94b6bd8a7707d00a4efac5d4905791ce09
Author: LiuYue <hangxingliu@gmail.com>
Date:   Tue Nov 28 14:12:18 2017 +0800

0.6.0 (contributed by @hangxingliu)

1. Add v0.6.0 in `CHANGELOG.md`
2. Change version to 0.6.0 in `package.json`
2. Add `contributors` in `package.json`
3. Add `package-lock.json`

### commit e521049c00857aa95cce7eb39b8e5e122dff9713
Author: LiuYue <hangxingliu@gmail.com>
Date:   Tue Nov 28 14:09:34 2017 +0800

Support multi-root workspace feature.

1. Add `promptForFolderIfNecessary` function in `extension.ts`.
2. Add `multi-root ready` to `keywords` in `package.json`.

Reference:
<https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs>

### commit 9943f92f435f84f2fd1d596c01dcb07777e121df
Author: LiuYue <hangxingliu@gmail.com>
Date:   Tue Nov 28 14:04:19 2017 +0800

Fix error and intellisense in extension.ts.

1. From `require` to import statement for intellisense in vscode.
2. Add Reference comment for vscode extension API intellisense and
compile success.
3. Completed interface declare for passing compile.
4. Some changes in enum to avoiding compile error.
5. Convert types from `url.URL` to `https.RequestOptions`
6. Fix callback function in `file.close` and `fs.unlink`

### commit 654d3fc3bde32d33f8e1ff13881a72a1594aa82a
Author: LiuYue <hangxingliu@gmail.com>
Date:   Tue Nov 28 13:57:32 2017 +0800

Add vscode.d.ts from vscode repository

Because vscode.d.ts is not in latest vscode npm package.
So extension developer should download it from vscode repository manual
for intellisense.
Reference: <https://github.com/Microsoft/vscode/issues/2810>

### commit 32c601d2971d90c9500eb6165db460b6cc789489
Author: LiuYue <hangxingliu@gmail.com>
Date:   Tue Nov 28 13:38:11 2017 +0800

Upgrade dependencies to latest (Included @types)

typescript from 1.x.x to 2.x.x

### CODE REVIEW

**Comment by CodeZombieCH** [comment]
Thanks for your contribution. I will take a look at your commits this Friday.

**Comment by ericblade** [comment]
@CodeZombieCH this'd be very useful. there's a few extensions that perform the same functionality as this, but it seems none of them support this feature. :(

**Comment by ericblade** [comment]
Great, and welcome back @CodeZombieCH  :)

**Comment by CodeZombieCH** [comment]
I just published version 0.6.0 on on the marketplace. This version has been completely updated to the latest vscode ecosystem and ships with updated npm packages.

@hangxingliu I would really like to give you the credit you deserve for your effort on adding support for  multi-root workspaces. If you have time and passion to recreate your work on supporting multi-root workspaces on the updated code base, I will be happy to merge your pull request. If I will not hear from you within the next couple of weeks, I will take the freedom to add the feature myself based on your contribution and mention you as contributor. Thank you very much.

**Comment by hangxingliu** [comment]
Thanks for your come back and approval of my work. And I will give your repository a pull request in a few days.

**Comment by hangxingliu** [comment]
@CodeZombieCH  new pull request: #14

**Pull request closed without merging**
